server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: unischedule
  static_configs:
  - targets:
      - [ localhost ]
    labels:
      service: "identity"
      app: "unischedule"
      __path__: /app/logs/identity/*.log
  - targets:
      - [ localhost ]
    labels:
      service: "events"
      app: "unischedule"
      __path__: /app/logs/events/*.log
  - targets:
      - [ localhost ]
    labels:
      service: "schedule"
      app: "unischedule"
      __path__: /app/logs/schedule/*.log
  - targets:
      - [ localhost ]
    labels:
      service: "bot"
      app: "unischedule"
      __path__: /app/logs/bot/*.log
