// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniSchedule.Schedule.Database;

#nullable disable

namespace UniSchedule.Schedule.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250219100244_RenameNotificationsToAnnouncements")]
    partial class RenameNotificationsToAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DayWeek", b =>
                {
                    b.Property<Guid>("DaysId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("DaysId", "WeekId");

                    b.HasIndex("WeekId");

                    b.ToTable("DayWeek");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("FinishedAt")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartedAt")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Subgroup")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("HasFixedSubgroups")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSubgroups")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Subgroup")
                        .HasColumnType("integer");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("DayWeek", b =>
                {
                    b.HasOne("UniSchedule.Schedule.Entities.Day", null)
                        .WithMany()
                        .HasForeignKey("DaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniSchedule.Schedule.Entities.Week", null)
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Announcement", b =>
                {
                    b.OwnsOne("UniSchedule.Schedule.Entities.Owned.AnnouncementTargetInfo", "Target", b1 =>
                        {
                            b1.Property<Guid>("AnnouncementId")
                                .HasColumnType("uuid");

                            b1.Property<List<Guid>>("ExcludedDepartments")
                                .HasColumnType("uuid[]");

                            b1.Property<List<int>>("ExcludedGrades")
                                .HasColumnType("integer[]");

                            b1.Property<List<Guid>>("ExcludedGroups")
                                .HasColumnType("uuid[]");

                            b1.Property<List<Guid>>("IncludedDepartments")
                                .HasColumnType("uuid[]");

                            b1.Property<List<int>>("IncludedGrades")
                                .HasColumnType("integer[]");

                            b1.Property<List<Guid>>("IncludedGroups")
                                .HasColumnType("uuid[]");

                            b1.HasKey("AnnouncementId");

                            b1.ToTable("Announcements");

                            b1.ToJson("Target");

                            b1.WithOwner()
                                .HasForeignKey("AnnouncementId");
                        });

                    b.Navigation("Target");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Class", b =>
                {
                    b.HasOne("UniSchedule.Schedule.Entities.Day", "Day")
                        .WithMany("Classes")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniSchedule.Schedule.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniSchedule.Schedule.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Location");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("UniSchedule.Schedule.Entities.Day", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
