name: release.yml
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy of release ${{ github.event.release.tag_name }} started
        run: echo Deploy of release ${{ github.event.release.tag_name }} started

      - name: Checkout backend repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN  }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ghcr.io/kiespetch1/backend:${{ github.event.release.tag_name }} -f Dockerfile .
          docker push ghcr.io/kiespetch1/backend:${{ github.event.release.tag_name }}
      
      - name: Clone frontend repo
        run: |
          git clone --branch ${{ github.event.release.tag_name }} --depth 1 https://github.com/kiespetch1/unischedule-frontend.git frontend

      - name: Build and push frontend Docker image
        working-directory: frontend
        run: |
          docker build -t ghcr.io/kiespetch/frontend:${{ github.event.release.tag_name }} -f Dockerfile .
          docker push ghcr.io/kiespetch/frontend:${{ github.event.release.tag_name }}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/kiespetch1/backend:latest
            docker pull ghcr.io/kiespetch1/frontend:latest
            
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 5000:5000 --restart always ghcr.io/kiespetch1/backend:latest
            
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 3000:3000 --restart always ghcr.io/kiespetch1/frontend:latest